notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 3.6

services:
  - docker

before_install:
  - travis_retry pip install yadage

script:
  - yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'
  - docker run -i -t --rm \
         -v `pwd`/data:/data \
         -v `pwd`/code:/code \
         -v `pwd`/results:/results \
         cmsopendata/cmssw_5_3_32 \
     /bin/bash -c 'cp -r /code/HiggsExample20112012 .; \
                   scram b; \
                   cd /code/HiggsExample20112012/Level3; \
                   cmsRun ./demoanalyzer_cfg_level3data.py'
  - ls -l `pwd`/results/DoubleMuParked2012C_10000_Higgs.root
  - docker run -i -t --rm \
         -v `pwd`/data:/data \
         -v `pwd`/code:/code \
         -v `pwd`/results:/results \
         cmsopendata/cmssw_5_3_32 \
     /bin/bash -c 'cp -r /code/HiggsExample20112012 .; \
                   scram b; \
                   cd /code/HiggsExample20112012/Level3; \
                   cmsRun demoanalyzer_cfg_level3MC.py'
  - ls -l `pwd`/results/Higgs4L1file.root
  - docker run -i -t --rm \
         -v `pwd`/data:/data \
         -v `pwd`/code:/code \
         -v `pwd`/results:/results \
         cmsopendata/cmssw_5_3_32 \
     /bin/bash -c 'cd /code/HiggsExample20112012/Level3; \
                   root -b -l -q ./M4Lnormdatall_lvl3.cc'
  - ls -l `pwd`/results/mass4l_combine_userlvl3.pdf